// Assembly Gmail Notifier Plus, Version 2.1.2.0

[assembly: System.Reflection.AssemblyVersion("2.1.2.*")]
[assembly: System.Reflection.AssemblyTitle("Gmail Notifier Plus")]
[assembly: System.Reflection.AssemblyConfiguration("")]
[assembly: System.Runtime.CompilerServices.RuntimeCompatibility(WrapNonExceptionThrows=true)]
[assembly: System.Reflection.AssemblyDescription("")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.Runtime.CompilerServices.CompilationRelaxations(8)]
[assembly: System.Reflection.AssemblyProduct("Gmail Notifier Plus")]
[assembly: System.Reflection.AssemblyCopyright("Copyright \x00a9 Baptiste Girod 2010, 2010 Andrew Powell / Shellscape Software")]
[assembly: System.Reflection.AssemblyTrademark("")]
[assembly: System.Reflection.AssemblyCompany("Shellscape Software")]
[assembly: System.Runtime.InteropServices.Guid("421a0043-b2ab-4b86-8dec-63ce3b8bd764")]
[assembly: System.Reflection.AssemblyFileVersion("2.1.2.*")]
[assembly: System.Resources.NeutralResourcesLanguage("")]
[assembly: System.Diagnostics.Debuggable(System.Diagnostics.DebuggableAttribute.DebuggingModes.IgnoreSymbolStoreSequencePoints)]